# Generated by Django 4.2.7 on 2026-01-26 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Topic name from roadmap', max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('instructions', models.TextField(help_text='Detailed assignment instructions')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('estimated_hours', models.IntegerField(default=2, help_text='Estimated time to complete')),
                ('total_points', models.IntegerField(default=100, help_text='Maximum points for this assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['topic', 'difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(default='📚', max_length=10)),
                ('difficulty_range', models.CharField(max_length=50)),
                ('estimated_weeks_min', models.IntegerField(default=6)),
                ('estimated_weeks_max', models.IntegerField(default=8)),
                ('topics_covered', models.JSONField(default=list)),
                ('prerequisites', models.JSONField(default=list)),
                ('learning_outcomes', models.JSONField(default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Topic name from roadmap', max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('article', 'Article'), ('link', 'External Link')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order within topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['topic', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_goal', models.CharField(choices=[('career_switch', 'Career Switch to Tech'), ('upskill', 'Upskill for Current Job'), ('personal_project', 'Build Personal Projects'), ('academic', 'Supplement Academic Studies'), ('freelance', 'Start Freelancing'), ('explore', 'Just Exploring')], max_length=50)),
                ('weekly_hours', models.IntegerField(default=6)),
                ('preferred_time', models.CharField(choices=[('early_morning', 'Early Morning (6-9 AM)'), ('evening', 'Evening (6-10 PM)'), ('weekend', 'Weekends'), ('flexible', 'Flexible')], max_length=20)),
                ('total_time_spent', models.IntegerField(default=0, help_text='Total time spent learning in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_data', models.JSONField()),
                ('user_answers', models.JSONField(blank=True, default=dict)),
                ('evaluation_results', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('custom_course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(choices=[('absolute_beginner', 'Absolute Beginner'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('confidence_score', models.IntegerField()),
                ('learning_pace', models.CharField(choices=[('slow', 'Slow'), ('moderate', 'Moderate'), ('fast', 'Fast')], max_length=20)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('estimated_weeks', models.IntegerField()),
                ('raw_results', models.JSONField()),
                ('roadmap_data', models.JSONField(blank=True, help_text='Generated roadmap structure', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.assessment')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('submission_text', models.TextField(blank=True, help_text='Text submission or answer')),
                ('submission_link', models.URLField(blank=True, help_text='Link to submission (GitHub, etc.)', max_length=500)),
                ('score', models.IntegerField(blank=True, help_text='Points earned', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Instructor feedback')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'assignment')},
            },
        ),
    ]
