# Generated by Django 4.2.7 on 2025-11-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-started_at']},
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='submitted_at',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='score',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='time_taken_seconds',
        ),
        migrations.AddField(
            model_name='assessment',
            name='custom_course_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='evaluation_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='user_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
