# Generated by Django 4.2.7 on 2025-11-02 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_assessment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
