# Generated by Django 4.2.8 on 2025-12-10 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_skillprofile_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Topic name from roadmap', max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('instructions', models.TextField(help_text='Detailed assignment instructions')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('estimated_hours', models.IntegerField(default=2, help_text='Estimated time to complete')),
                ('total_points', models.IntegerField(default=100, help_text='Maximum points for this assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['topic', 'difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Topic name from roadmap', max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('article', 'Article'), ('link', 'External Link')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order within topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['topic', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('submission_text', models.TextField(blank=True, help_text='Text submission or answer')),
                ('submission_link', models.URLField(blank=True, help_text='Link to submission (GitHub, etc.)', max_length=500)),
                ('score', models.IntegerField(blank=True, help_text='Points earned', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Instructor feedback')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'assignment')},
            },
        ),
    ]
