# Generated by Django 4.2.8 on 2025-12-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignment_topicresource_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='total_time_spent',
            field=models.IntegerField(default=0, help_text='Total time spent learning in minutes'),
        ),
    ]
