# Generated by Django 4.2.8 on 2025-12-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_learnerprofile_total_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillprofile',
            name='roadmap_data',
            field=models.JSONField(blank=True, help_text='Generated roadmap structure', null=True),
        ),
    ]
