# Generated by Django 4.2.8 on 2026-01-03 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_skillprofile_roadmap_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('assessment_completed', models.BooleanField(default=False, help_text='TRUE = Assessment locked, NO reassessment allowed')),
                ('assessment_date', models.DateTimeField(blank=True, null=True)),
                ('initial_skill_level', models.CharField(blank=True, max_length=20, null=True)),
                ('roadmap_generated', models.BooleanField(default=False)),
                ('roadmap_version', models.IntegerField(default=0)),
                ('overall_progress', models.FloatField(default=0.0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course'), ('user', 'custom_course_name')},
            },
        ),
        migrations.CreateModel(
            name='PersonalizedRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_data', models.JSONField(help_text='Full roadmap structure')),
                ('version', models.IntegerField(default=1)),
                ('refinement_history', models.JSONField(default=list)),
                ('current_topic_index', models.IntegerField(default=0)),
                ('unlocked_topic_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_evolved', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_roadmap', to='core.courseenrollment')),
            ],
            options={
                'verbose_name': 'Personalized Roadmap',
                'verbose_name_plural': 'Personalized Roadmaps',
            },
        ),
        migrations.CreateModel(
            name='TopicQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('custom_course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('difficulty', models.CharField(max_length=20)),
                ('questions', models.JSONField(help_text='MCQ questions')),
                ('passing_score', models.IntegerField(default=70)),
                ('time_limit', models.IntegerField(blank=True, help_text='Minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_quizzes', to='core.course')),
            ],
            options={
                'unique_together': {('topic_name', 'course'), ('topic_name', 'custom_course_name')},
            },
        ),
        migrations.CreateModel(
            name='InitialAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_data', models.JSONField(help_text='MCQ questions')),
                ('user_answers', models.JSONField(help_text="User's answers")),
                ('total_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('detected_skill_level', models.CharField(max_length=20)),
                ('weak_topics', models.JSONField(default=list)),
                ('strong_topics', models.JSONField(default=list)),
                ('skill_gaps', models.JSONField(default=list)),
                ('incorrect_answers', models.JSONField(default=list)),
                ('time_taken', models.IntegerField(default=0, help_text='Seconds')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initial_assessment', to='core.courseenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='TopicQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1)),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('correct_count', models.IntegerField()),
                ('incorrect_count', models.IntegerField()),
                ('time_spent', models.IntegerField(help_text='Seconds')),
                ('user_answers', models.JSONField(default=dict)),
                ('weak_concepts', models.JSONField(default=list)),
                ('passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.topicquiz')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='core.personalizedroadmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'quiz', '-completed_at'], name='core_topicq_user_id_a20b69_idx')],
            },
        ),
    ]
