# Generated by Django 4.2.8 on 2026-01-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_courseenrollment_personalizedroadmap_topicquiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialassessment',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='personalizedroadmap',
            name='enrollment',
        ),
        migrations.AlterUniqueTogether(
            name='topicquiz',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topicquiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='topicquizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='topicquizattempt',
            name='roadmap',
        ),
        migrations.RemoveField(
            model_name='topicquizattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='CourseEnrollment',
        ),
        migrations.DeleteModel(
            name='InitialAssessment',
        ),
        migrations.DeleteModel(
            name='PersonalizedRoadmap',
        ),
        migrations.DeleteModel(
            name='TopicQuiz',
        ),
        migrations.DeleteModel(
            name='TopicQuizAttempt',
        ),
    ]
